# Generated by Django 5.2.4 on 2025-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
