# Generated by Django 5.2.4 on 2025-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='delivery_address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
