# Generated by Django 5.2.4 on 2025-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_alter_rental_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='delivery_address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
