# Generated by Django 5.2.4 on 2025-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_rental_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='delivery_address',
            field=models.TextField(default='Not provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_days',
            field=models.PositiveIntegerField(),
        ),
    ]
